### ISSUE TITLE
Where to add login options?

### ISSUE THREAD

**Issue by veego** [erikhagreis/fb-sdk-wrapper#1]
Thanks for this nice wrapper, finally I found easy to use one, and implemented in VueJS in minutes :)

If I do:
```
Facebook.login({scope: 'public_profile,email,user_friends', return_scopes: true})
    .then((response) => {
        console.log(response)
    })
```
the `scope` and `return_scopes` options not working (only public profile in dialog, response without scopes). But if I do it via `FB` it works:  
```
let fb = Facebook.getGlobalFB()
      fb.login(function (response) {
        console.log(response)
      }, {scope: 'public_profile,email,user_friends', return_scopes: true})
```
How to provide login options?

**Comment by erikhagreis** [comment]
Hey Veego, happy you like it :) 

Actually I noticed a bug yesterday where the login params were not passed down from the wrapper to FB. This should be fixed in v0.2.0. I've just checked this and it 'works for me'™.  

Let me know if you still have any issues and I'll look into them. 

This lib is fresh so probably a little rough around the edges still!
